export const TOKEN_RECEIVED='TOKEN_RECEIVED';
export const TOKEN_RECEIVE_FAILED='TOKEN_RECEIVED_FAILED';
export const TOKEN_REVOKED='TOKEN_REVOKED';
export const TOKEN_REVOKE_FAILED='TOKEN_REVOKED_FAILED';
export const IS_ADMIN='IS_ADMIN';
export const IS_NOT_ADMIN='IS_NOT_ADMIN';
export const REDIRECT_ERROR='REDIRECT_ERROR';

